version: '3.8'
services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      mysql-notify:
        condition: service_healthy

  mysql-notify:
    image: mysql:8
    container_name: mysql_notify
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notify_db
      MYSQL_USER: notify_user
      MYSQL_PASSWORD: notify_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq-notify:
    image: rabbitmq:3-management
    container_name: rabbitmq_notify
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  notification-service:
    build: ./services/notification-service
    container_name: notification_service
    env_file:
      - .env
    depends_on:
      mysql-notify:
        condition: service_healthy
      rabbitmq-notify:
        condition: service_healthy
    ports:
      - "4001:4001"

  emitter-service:
    build: ./services/emitter-service
    container_name: emitter_service
    env_file:
      - .env
    depends_on:
      rabbitmq-notify:
        condition: service_healthy
    ports:
      - "4002:4002"

volumes:
  mysql_data: